Generate configuration YAML from ImplementationGuide
FHIR/GoFSH pull request #2
Opened 2020-09-24 18:03 UTC by mint-thompson

Completes task [CIMPL-530](https://standardhealthrecord.atlassian.net/browse/CIMPL-530).

When an ImplementationGuide JSON file is present, try to use it to create a config file. Since canonical and fhirVersion are required in the configuration, those are also required from the JSON. Since configuration isn't stored directly in the IG or anywhere else, goFSH assumes that the IG's url is in FSH's preferred format and works from there. Optional fields for id, name, status, and version are also included when available. If more than one ImplementationGuide is found, whichever one is found first is used, and a message is logged.

2020-09-30 21:07 UTC, ngfreiter reviewed
This looked good to me overall, but I was wondering if the `FSHOnly` flag should be set in the configuration, and that led me down a bit of a rabbit hole of wondering how we want to structure the output of goFSH. Should the output of goFSH be a `FSHOnly` project structure, so just a `sushi-config.yaml` and some `fsh` files in `input/fsh`, or should the output be more similar to the output of `sushi --init`, where the project is ready to be used with the IG Publisher.

If we are going with the `FSHOnly` structure, it ends up raising the question (which I wish I had thought of way earlier) of if we need to generate a config at all, when an IG.json exists. Because SUSHI can extract config from IG.json, so we could just copy it to the output and let SUSHI extract.

But if we aren't going with the `FSHOnly` structure, and we would set up a project structure so that SUSHI is generating an ImplementationGuide.json file, then I do think it is necessary to extract a config, but then in this case the config would need to include more properties so that the SUSHI generated ImplementationGuide.json matches the original input to goFSH. If we are going with this approach, then I don't think it is appropriate to add that to the scope of this PR. I just wanted to bring up these questions that are swirling inside my head in case these questions have already been answered and I'm just forgetting.

2020-09-30 21:39 UTC, cmoesel commented
I think even a `FSHOnly` `config.yaml` might be helpful because it gives them a starting point if they want to use more advanced features later.  If we really wanted to, we could put a comment at the top of the file that says if you do not need IG features, you can delete this `config.yaml` (but I don't know if that's necessary).

Regarding "to IG or not to IG": How do you feel about `gofsh --ig /path/to/input`?  So, default to `FSHOnly` but generate a starter IG by request?

2020-10-04 18:00 UTC, cmoesel requested changes
Looks good!  I only had one minor suggestion to tighten up the regex a bit when extracting the canonical.

2020-10-05 16:55 UTC, ngfreiter reviewed
Looking good, I just had a few very minor comments.

2020-10-05 16:55 UTC, ngfreiter commented on src/processor/Package.ts
> +            resource.config.id ? `id ${resource.config.id}` : 'unknown id'
Here as a backup, instead of `unknown id` we could consider outputting the `canonical`, since we know that will be defined right?

2020-10-05 16:55 UTC, ngfreiter commented on test/processor/ConfigurationProcessor.test.ts
> +  it('should not create a Configuration with a fhirVersion', () => {
I think this should say: "should not create a Configuration **without** a fhirVersion".

2020-10-05 16:55 UTC, ngfreiter commented on src/processor/Package.ts
> +            resource.config.id ? `id ${resource.config.id}` : 'unknown id'
I wasn't seeing a test for the logic of skipping previous IGs here. Could you add a test for that?

2020-10-06 19:12 UTC, ngfreiter commented
@mint-thompson this looks good to me. Once the conflicts are resolved I can give this one last look and approve.

2020-10-07 13:43 UTC, ngfreiter approved these changes
Looks good!

2020-10-07 13:46 UTC, cmoesel approved these changes

2020-10-07 13:47 UTC, merged