Support for extensions on primitives (such as type._targetProfile.extension)
FHIR/GoFSH pull request #214
Opened 2023-03-31 16:01 UTC by cmoesel

Adds support for properly generating rules for ids and extensions on primitive values. Prior to this PR, they were dropped. This required a change in SUSHI, so the version of SUSHI was updated. This in turn caused additional regressions related to a fix in SUSHI 2.9.0 that made it so an instance's `id` getter would consult assignment rules for `id` overrides (see: https://github.com/FHIR/sushi/pull/1198). Most of the changes in this PR are to update GoFSH to work properly with this new way of handling Instance ids. Changes included:
* setting inline instances via name rather than id
* updating the name optimizer to fix up changed names in inline instance assignments

There was also some ambiguity / confusion related to a test profile having the name Patient (which conflicts with a resource name), so I updated the fixture and tests to reflect a unique name, and added a new fixture for a profile named Patient to test that name clash condition specifically.

2023-03-31 16:12 UTC, cmoesel commented
Converted to DRAFT after comparing outputs on US Core and finding some unexpected differences.

2023-04-04 20:21 UTC, cmoesel commented
OK. All issues have been addressed and this PR is ready for review.

2023-04-05 15:21 UTC, mint-thompson requested changes
This looks real good. I found one small typo in a comment, but that's the only thing that I found. Thank you!

2023-04-05 19:48 UTC, mint-thompson submitted a review, later dismissed

2023-04-06 14:30 UTC, jafeltra commented
The code all makes sense to me. I did have one question. When I ran GoFSH using the `-f` fishing trip flag on the US Core Document Reference that is in the issue, I see that "DocumentReference.author" `type` is removed in the round trip. Is that expected? I'm heading into a meeting now, so I wanted to leave this, but I can keep looking into/thinking about it after!

2023-04-06 14:52 UTC, cmoesel commented
Oh my goodness. Thank you for mentioning the roundtrip, @jafeltra. When I run the roundtrip, I see a lot of this:
> error The element or path you referenced does not exist: type._targetProfile[0].extension.url

I totally messed it up. The correct path in FSH is not `type._targetProfile[0].extension.url`; it is `type.targetProfile[0].extension.url`. The leading `_` is part of the JSON serialization but not part of FSH path specification. I need to fix this!

2023-04-07 15:42 UTC, cmoesel commented
This PR is back in business. The `_` issues were addressed in 42954be.

@jafeltra, you said that you saw "DocumentReference.author" `type` removed when you round-tripped, but I wasn't able to reproduce that. I see GoFSH produce the following rules for USCore DocumentReference:
```
* author only Reference(USCorePractitionerProfile or USCoreOrganizationProfile or USCorePatientProfile or USCorePractitionerRoleProfile or USCoreRelatedPersonProfile or Device)
* author MS
* author ^type.targetProfile[0].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = true
* author ^type.targetProfile[+].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = false
* author ^type.targetProfile[+].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = false
* author ^type.targetProfile[+].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = false
* author ^type.targetProfile[+].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = false
* author ^type.targetProfile[+].extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support"
* author ^type.targetProfile[=].extension.valueBoolean = false
```
and I see it reflected in the generated differential from SUSHI:
```json
{
  "id": "DocumentReference.author",
  "path": "DocumentReference.author",
  "type": [
    {
      "code": "Reference",
      "targetProfile": [
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner",
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization",
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient",
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole",
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-relatedperson",
        "http://hl7.org/fhir/StructureDefinition/Device"
      ],
      "_targetProfile": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": true
            }
          ]
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": false
            }
          ]
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": false
            }
          ]
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": false
            }
          ]
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": false
            }
          ]
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/elementdefinition-type-must-support",
              "valueBoolean": false
            }
          ]
        }
      ]
    }
  ],
  "mustSupport": true
}
```
Can you try again? I am using US Core 5.0.1 in case that matters.

2023-04-11 14:52 UTC, jafeltra commented
Ah, mixed in with the errors about paths were errors that the definition couldn't be found for those profiles because I was only running it on the one DocumentReference resource. When I use this branch and run GoFSH on the full US Core, I no longer see either of those types of errors.

I didn't look through the full fishing trip diffs, but the resources I did look at all had differences that were fine and the `targetProfile` extensions are processed by GoFSH and SUSHI correctly.

2023-04-18 18:10 UTC, mint-thompson approved these changes

2023-04-18 19:10 UTC, merged