Special handling for CodeableReference type constraints
FHIR/GoFSH pull request #221
Opened 2023-05-18 16:33 UTC by mint-thompson

Fixes #220 and completes task [CIMPL-1100](https://standardhealthrecord.atlassian.net/browse/CIMPL-1100).

CodeableReference elements have to be handled a bit carefully because they are sort of like Reference elements, but the FSH Reference keyword usually tries to make things a Reference type. This can lead to issues when a choice element has a CodeableReference type. Make separate rules for constraining the type to CodeableReference and for constraining the target profiles for CodeableReference.

When round-tripping the file in the issue, the only differences are in the ordering of properties. The starting and ending JSON are logically equal.

One thing I noticed that may or may not be in scope to do here is that `OnlyRuleExtractor.process` can't really handle a case where an element with type `Reference` or `CodeableReference` has both `profile` and `targetProfile` defined. As far as I know, nothing in the spec prohibits this, so that will need to be addressed.

2023-05-24 21:27 UTC, cmoesel requested changes
I hadn't thought too much about how this works w/ AddElement rules. In particular, I hadn't fully thought out the need for something like this when `Reference` and `CodeableReference` are involved:
```
* med[x] 0..* Reference(Medication or Immunization) or CodeableReference "Medication or Immunization" "Medication or Immunization"
* medCodeableReference only Reference(Medication or Immunization)
```
Unfortunately, the second rule is not valid in a logical or resource because you cannot introduce slices in a logical or resource (only in profiles and extensions). So we're at an impasse. We'll need to discuss this further.

2023-05-24 21:27 UTC, cmoesel commented on test/extractor/AddElementRuleExtractor.test.ts
> +      const expectedOnly = new ExportableOnlyRule('cheeseCodeableReference');
Oh... I hadn't thought of this scenario, but... this is actually a problem. The only way to apply the reference to the `CodeableReference` is via a type slice path, but... slices aren't allowed in logical models! SUSHI doesn't yell, but the IG Publisher does:
> Rule sdf-1: 'Element paths must be unique unless the structure is a constraint' Failed

So, creating a type slice here is not a viable option. Although we _could_ use a caret rule assignment, that's awful -- and we can't expect our users to do that. We may have to introduce `CodeableReference(A or B)` after all... I'll talk to Mark.

2023-06-01 18:48 UTC, mint-thompson commented
This PR is on hold until there are some changes in SUSHI to support a `CodeableReference` keyword.

2023-07-12 15:29 UTC, closed without merging

2023-07-12 15:29 UTC, mint-thompson commented
closed, there will be a new PR that uses the `CodeableReference` keyword.